/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jrpg.gui;


/**
 *
 * @author Caleb Smith
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                WindowPlaySound(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Yuuki");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(560, 20, 210, 60);

        jLabel1.setText("__________________________");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(590, 71, 180, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrpg/gui/New Game.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewChangeIcon(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewResetIcon(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 90, 180, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Caleb\\Documents\\NDSU\\2012 Semester 1\\CSCI 161\\Projects\\Group Project\\Gui\\Load Game.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoadChangeIcon(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoadResetIcon(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 140, 190, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrpg/gui/Options.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OptionsChangeIcon(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OptionsResetIcon(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(590, 190, 140, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrpg/gui/Exit.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitChangeIcon(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitResetIcon(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(620, 240, 80, 60);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrpg/gui/titleBackground.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewChangeIcon(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewChangeIcon
        // TODO add your handling code here:
        jLabel2.setIcon( new javax.swing.ImageIcon(getClass().getResource("/jrpg/gui/New Game Hi.png")));     
    }//GEN-LAST:event_NewChangeIcon

    private void NewResetIcon(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewResetIcon
        // TODO add your handling code here:
        jLabel2.setIcon( new javax.swing.ImageIcon(getClass().getResource("/jrpg/gui/New Game.png")));
    }//GEN-LAST:event_NewResetIcon

    private void LoadChangeIcon(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadChangeIcon
        // TODO add your handling code here:
        jLabel4.setIcon( new javax.swing.ImageIcon(getClass().getResource("/jrpg/gui/Load Game Hi.png")));
    }//GEN-LAST:event_LoadChangeIcon

    private void LoadResetIcon(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadResetIcon
        // TODO add your handling code here:
        jLabel4.setIcon( new javax.swing.ImageIcon(getClass().getResource("/jrpg/gui/Load Game.png")));
    }//GEN-LAST:event_LoadResetIcon

    private void OptionsChangeIcon(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsChangeIcon
        // TODO add your handling code here:
        jLabel5.setIcon( new javax.swing.ImageIcon(getClass().getResource("/jrpg/gui/Options Hi.png")));
    }//GEN-LAST:event_OptionsChangeIcon

    private void OptionsResetIcon(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsResetIcon
        // TODO add your handling code here:
        jLabel5.setIcon( new javax.swing.ImageIcon(getClass().getResource("/jrpg/gui/Options.png")));
    }//GEN-LAST:event_OptionsResetIcon

    private void ExitChangeIcon(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitChangeIcon
        // TODO add your handling code here:
        jLabel6.setIcon( new javax.swing.ImageIcon(getClass().getResource("/jrpg/gui/Exit Hi.png")));
    }//GEN-LAST:event_ExitChangeIcon

    private void ExitResetIcon(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitResetIcon
        // TODO add your handling code here:
        jLabel6.setIcon( new javax.swing.ImageIcon(getClass().getResource("/jrpg/gui/Exit.png")));
    }//GEN-LAST:event_ExitResetIcon

    private void ExitClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitClicked

    private void WindowPlaySound(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WindowPlaySound
        // TODO add your handling code here:
    }//GEN-LAST:event_WindowPlaySound

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
