package yuuki.gui.UI;

import java.io.FileInputStream;
import java.io.IOException;
import sun.audio.AudioData;
import sun.audio.AudioDataStream;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Caleb Smtih
 * @version 11/13/12
 */
public class OptionsMenu extends javax.swing.JFrame {
boolean musicOnChecked = true;
boolean musicOffChecked = false;
boolean effectsOnChecked = true;
boolean effectsOffChecked = false;

    /**
     * Creates new form OptionsMenu
     */
    public OptionsMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOptionsText = new javax.swing.JLabel();
        lblBtnApply = new javax.swing.JLabel();
        lblMusicRadialSelectOff = new javax.swing.JLabel();
        lblEffectsRadialSelectOff = new javax.swing.JLabel();
        lblText2 = new javax.swing.JLabel();
        lblMusicRadialSelectOn = new javax.swing.JLabel();
        lblEffectsRadialSelectOn = new javax.swing.JLabel();
        lblOptionsBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(16, 38, 800, 600));
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(2147483647, 2147483647, 2147483647, 2147483647));
        getContentPane().setLayout(null);

        lblOptionsText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsText.png"))); // NOI18N
        getContentPane().add(lblOptionsText);
        lblOptionsText.setBounds(10, 0, 580, 200);

        lblBtnApply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsBtnApply.png"))); // NOI18N
        lblBtnApply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnApply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApplyClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnApplyEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnApplyExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBtnApplyPressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBtnApplyReleased(evt);
            }
        });
        getContentPane().add(lblBtnApply);
        lblBtnApply.setBounds(10, 510, 171, 76);

        lblMusicRadialSelectOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png"))); // NOI18N
        lblMusicRadialSelectOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMusicRadialSelectOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicOffClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                musicOffEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                musicOffExited(evt);
            }
        });
        getContentPane().add(lblMusicRadialSelectOff);
        lblMusicRadialSelectOff.setBounds(720, 90, 30, 30);

        lblEffectsRadialSelectOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png"))); // NOI18N
        lblEffectsRadialSelectOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEffectsRadialSelectOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                effectsOffClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                effectsOffEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                effectsOffExited(evt);
            }
        });
        getContentPane().add(lblEffectsRadialSelectOff);
        lblEffectsRadialSelectOff.setBounds(721, 160, 30, 30);

        lblText2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsText2.png"))); // NOI18N
        getContentPane().add(lblText2);
        lblText2.setBounds(640, 80, 70, 110);

        lblMusicRadialSelectOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png"))); // NOI18N
        lblMusicRadialSelectOn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMusicRadialSelectOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicOnClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                musicOnEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                musicOnExited(evt);
            }
        });
        getContentPane().add(lblMusicRadialSelectOn);
        lblMusicRadialSelectOn.setBounds(600, 90, 30, 30);

        lblEffectsRadialSelectOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png"))); // NOI18N
        lblEffectsRadialSelectOn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEffectsRadialSelectOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                effectsOnClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                effectsOnEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                effectsOnExited(evt);
            }
        });
        getContentPane().add(lblEffectsRadialSelectOn);
        lblEffectsRadialSelectOn.setBounds(603, 160, 30, 30);

        lblOptionsBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsBackground.png"))); // NOI18N
        getContentPane().add(lblOptionsBackground);
        lblOptionsBackground.setBounds(0, 0, 800, 600);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-816)/2, (screenSize.height-638)/2, 816, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnApplyEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnApplyEntered
        // On Mouseover changes lblBtnApply's Icon.
        lblBtnApply.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsBtnApplyFocused.png")));
        if(effectsOffChecked == false)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("/yuuki/gui/UI/GuiSoundAssets/onHover.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
        }
    }//GEN-LAST:event_lblBtnApplyEntered

    private void lblBtnApplyExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnApplyExited
        // On Mouseover off changes lblBtnApply's Icon.
        lblBtnApply.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsBtnApply.png")));
    }//GEN-LAST:event_lblBtnApplyExited

    private void lblBtnApplyPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnApplyPressed
        // On Mouse Press moves lblBtnApply Down and Right.
        lblBtnApply.setBounds(12, 512, 171, 76);
    }//GEN-LAST:event_lblBtnApplyPressed

    private void lblBtnApplyReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnApplyReleased
        // TODO add your handling code here:
        lblBtnApply.setBounds(10, 510, 171, 76);
    }//GEN-LAST:event_lblBtnApplyReleased

    private void musicOnEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicOnEntered
        // Code checks to see which state lblMusicRadialSelectOn is in, and performs the appropriate action.
        if(musicOnChecked == true)
        {
            lblMusicRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOnHover.png")));
        }
        else
        {
            lblMusicRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOffHover.png")));
        }
        if(effectsOffChecked == false)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("/yuuki/gui/UI/GuiSoundAssets/onHover.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
        }
    }//GEN-LAST:event_musicOnEntered

    private void musicOnExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicOnExited
        // Code checks to see which state lblMusicRadialSelectOn is in, and performs the appropriate action.
        if(musicOnChecked == true)
        {
            lblMusicRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png")));
        }
        else
        {
            lblMusicRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png")));
        }
    }//GEN-LAST:event_musicOnExited

    private void effectsOnEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_effectsOnEntered
        // Code checks to see which state lblMusicRadialSelectOn is in, and performs the appropriate action.
        if(effectsOnChecked == true)
        {
            lblEffectsRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOnHover.png")));
        }
        else
        {
            lblEffectsRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOffHover.png")));
        }        
        if(effectsOffChecked == false)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("/yuuki/gui/UI/GuiSoundAssets/onHover.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
        }
    }//GEN-LAST:event_effectsOnEntered

    private void effectsOnExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_effectsOnExited
        // Code checks to see which state lblMusicRadialSelectOn is in, and performs the appropriate action.
        if(effectsOnChecked == true)
        {
            lblEffectsRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png")));
        }
        else
        {
            lblEffectsRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png")));
        }
    }//GEN-LAST:event_effectsOnExited

    private void musicOffEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicOffEntered
        // Code checks to see which state lblMusicRadialSelectOn is in, and performs the appropriate action.
        if(musicOffChecked == true)
        {
            lblMusicRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOnHover.png")));
        }
        else
        {
            lblMusicRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOffHover.png")));
        }
        if(effectsOffChecked == false)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("/yuuki/gui/UI/GuiSoundAssets/onHover.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
        }
    }//GEN-LAST:event_musicOffEntered

    private void effectsOffEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_effectsOffEntered
        // Code checks to see which state lblMusicRadialSelectOn is in, and performs the appropriate action.
        if(effectsOffChecked == true)
        {
            lblEffectsRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOnHover.png")));
        }
        else
        {
            lblEffectsRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOffHover.png")));
        }
        if(effectsOffChecked == false)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("/yuuki/gui/UI/GuiSoundAssets/onHover.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
        }
    }//GEN-LAST:event_effectsOffEntered

    private void musicOffExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicOffExited
        // Code checks to see which state lblMusicRadialSelectOn is in, and performs the appropriate action.
        if(musicOffChecked == true)
        {
            lblMusicRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png")));
        }
        else
        {
            lblMusicRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png")));
        }
        
    }//GEN-LAST:event_musicOffExited

    private void effectsOffExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_effectsOffExited
        // Code checks to see which state lblMusicRadialSelectOn is in, and performs the appropriate action.
        if(effectsOffChecked == true)
        {
            lblEffectsRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png")));
        }
        else
        {
            lblEffectsRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png")));
        }
    }//GEN-LAST:event_effectsOffExited

    private void musicOnClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicOnClicked
        // Invert checked properties, and change lbl Icons.
        if(musicOnChecked == true)
        {
        musicOnChecked = false;
        musicOffChecked = true;
        lblMusicRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png")));
        lblMusicRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png")));
        }
        else
        {
        musicOnChecked = true;
        musicOffChecked = false;
        lblMusicRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png")));
        lblMusicRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png")));
        }
        if(effectsOffChecked == false)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("/yuuki/gui/UI/GuiSoundAssets/onSelect.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
        }
    }//GEN-LAST:event_musicOnClicked

    private void musicOffClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicOffClicked
        // Invert checked properties, and change lbl Icons.
        if(musicOffChecked == true)
        {
        musicOnChecked = true;
        musicOffChecked = false;
        lblMusicRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png")));
        lblMusicRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png")));
        }
        else
        {
        musicOnChecked = false;
        musicOffChecked = true;
        lblMusicRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png")));
        lblMusicRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png")));
        }
        if(effectsOffChecked == false)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("/yuuki/gui/UI/GuiSoundAssets/onSelect.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
        }
    }//GEN-LAST:event_musicOffClicked

    private void effectsOnClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_effectsOnClicked
        // Invert checked properties, and change lbl Icons.
        if(effectsOnChecked == true)
        {
        effectsOnChecked = false;
        effectsOffChecked = true;
        lblEffectsRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png")));
        lblEffectsRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png")));
        }
        else
        {
        effectsOnChecked = true;
        effectsOffChecked = false;
        lblEffectsRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png")));
        lblEffectsRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png")));
        }
        if(effectsOffChecked == false)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("/yuuki/gui/UI/GuiSoundAssets/onSelect.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
        }
    }//GEN-LAST:event_effectsOnClicked

    private void effectsOffClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_effectsOffClicked
        // // Invert checked properties, and change lbl Icons.
        
        if(effectsOffChecked == true)
        {
        effectsOnChecked = true;
        effectsOffChecked = false;
        lblEffectsRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png")));
        lblEffectsRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png")));
        }
        else
        {
        effectsOnChecked = false;
        effectsOffChecked = true;
        lblEffectsRadialSelectOn.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOff.png")));
        lblEffectsRadialSelectOff.setIcon( new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/OptionsMenuGuiAssets/OptionsRadialSelectOn.png")));
        }
        if(effectsOffChecked == false)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("/yuuki/gui/UI/GuiSoundAssets/onSelect.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
        }
    }//GEN-LAST:event_effectsOffClicked

    private void btnApplyClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplyClicked
        // Handles btnApply clicked event.
        if(effectsOffChecked == false)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("/yuuki/gui/UI/GuiSoundAssets/onSelect.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
        }
        setVisible(false);
    }//GEN-LAST:event_btnApplyClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBtnApply;
    private javax.swing.JLabel lblEffectsRadialSelectOff;
    private javax.swing.JLabel lblEffectsRadialSelectOn;
    private javax.swing.JLabel lblMusicRadialSelectOff;
    private javax.swing.JLabel lblMusicRadialSelectOn;
    private javax.swing.JLabel lblOptionsBackground;
    private javax.swing.JLabel lblOptionsText;
    private javax.swing.JLabel lblText2;
    // End of variables declaration//GEN-END:variables
}
