/*
 * This JFrame accepts text input from lable's text property.
 * It offer's navigation back to the main menu, and into the game.
 */
package yuuki.gui.UI;

import java.io.FileInputStream;
import java.io.IOException;
import sun.audio.AudioData;
import sun.audio.AudioDataStream;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Caleb Smith
 * @version 10/11/12
 */
public class PlayerName extends javax.swing.JFrame {
    boolean blnStartGame = false;
    boolean blnSound = true;
    String usersName = "Player 1";
    
    public String getUsersName()
    {
        return usersName;
    }
    public boolean getPlayStatus()
    {
        return blnStartGame;
    }
    /**
     * Creates new form PlayerName
     */
    public PlayerName() {
        initComponents();
        txtPlayerName.setSelectionStart(0);
        txtPlayerName.setSelectionEnd(11); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPlayerName = new javax.swing.JTextField();
        lblBtnMainMenu = new javax.swing.JLabel();
        lblBtnBeginGame = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(16, 38, 800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        txtPlayerName.setFont(new java.awt.Font("Segoe Print", 0, 76)); // NOI18N
        txtPlayerName.setForeground(new java.awt.Color(255, 204, 0));
        txtPlayerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlayerName.setText("Player Name");
        txtPlayerName.setBorder(null);
        txtPlayerName.setCaretColor(new java.awt.Color(255, 204, 0));
        txtPlayerName.setOpaque(false);
        txtPlayerName.setSelectedTextColor(new java.awt.Color(255, 204, 0));
        txtPlayerName.setSelectionColor(new java.awt.Color(128, 126, 126));
        getContentPane().add(txtPlayerName);
        txtPlayerName.setBounds(79, 123, 648, 210);

        lblBtnMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/PlayerNameGuiAssets/PlayerNameMainMenu.png"))); // NOI18N
        lblBtnMainMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnMainMenuClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnMainMenuEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnMainMenuExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBtnMainMenuPressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBtnMainMenuReleased(evt);
            }
        });
        getContentPane().add(lblBtnMainMenu);
        lblBtnMainMenu.setBounds(10, 460, 170, 100);

        lblBtnBeginGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/PlayerNameGuiAssets/PlayerNameBeginGame.png"))); // NOI18N
        lblBtnBeginGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnBeginGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnBeginGameClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnBeginGame(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnBeginGameExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBtnBeginGamePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBtnBeginGameReleased(evt);
            }
        });
        getContentPane().add(lblBtnBeginGame);
        lblBtnBeginGame.setBounds(620, 460, 170, 100);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yuuki/gui/UI/PlayerNameGuiAssets/CaveWall.png"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 800, 600);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-816)/2, (screenSize.height-638)/2, 816, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnMainMenuEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnMainMenuEntered
        // Handles lblBtnMainMenu on Mouseover.
        lblBtnMainMenu.setIcon( new javax.swing.ImageIcon(getClass().getResource("PlayerNameMainMenuHi.png")));
        if(blnSound == true)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("onHover.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
        }
    }//GEN-LAST:event_lblBtnMainMenuEntered

    private void lblBtnMainMenuExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnMainMenuExited
        // Handles lblBtnMainMenu on Mouseover off.
        lblBtnMainMenu.setIcon( new javax.swing.ImageIcon(getClass().getResource("PlayerNameMainMenu.png")));
    }//GEN-LAST:event_lblBtnMainMenuExited

    private void lblBtnMainMenuClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnMainMenuClicked
        // Handles lblBtnMainMenuClicked click event.
        if(blnSound == true)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("onSelect.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
        }
        setVisible(false);
    }//GEN-LAST:event_lblBtnMainMenuClicked

    private void lblBtnMainMenuPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnMainMenuPressed
        // Handles lblBtnMainMenuPressed Mouse Click Down Event.
        lblBtnMainMenu.setBounds(12, 462, 170, 100);
    }//GEN-LAST:event_lblBtnMainMenuPressed

    private void lblBtnMainMenuReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnMainMenuReleased
        // Handles lblBtnMainMenuPressed Mouse Click Up Event.
        lblBtnMainMenu.setBounds(10, 460, 170, 100);
    }//GEN-LAST:event_lblBtnMainMenuReleased

    private void lblBtnBeginGame(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnBeginGame
        // Handles lblBtnMainMenu on Mouseover.
        lblBtnBeginGame.setIcon( new javax.swing.ImageIcon(getClass().getResource("PlayerNameBeginGameHi.png")));
        if(blnSound == true)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("onHover.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
        }
    }//GEN-LAST:event_lblBtnBeginGame

    private void lblBtnBeginGameExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnBeginGameExited
        // Handles lblBtnBeginGame on Mouseover off.
        lblBtnBeginGame.setIcon( new javax.swing.ImageIcon(getClass().getResource("PlayerNameBeginGame.png")));
    }//GEN-LAST:event_lblBtnBeginGameExited

    private void lblBtnBeginGamePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnBeginGamePressed
        // Handles lblBtnBeginGame on Press.
        lblBtnBeginGame.setBounds(622, 462, 170, 100);
    }//GEN-LAST:event_lblBtnBeginGamePressed

    private void lblBtnBeginGameReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnBeginGameReleased
        // Handles lblBtnBeginGame on Release.
        lblBtnBeginGame.setBounds(620, 460, 170, 100);
    }//GEN-LAST:event_lblBtnBeginGameReleased

    private void lblBtnBeginGameClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnBeginGameClicked
        // Handles lblBtnBeginGame on Click.
        blnStartGame = true;
        usersName = txtPlayerName.getText();
        if(blnSound == true)
        {
            AudioPlayer BGMPlayer = AudioPlayer.player;
            AudioStream BGM;
            AudioData BGMData;
            try
            {
            BGM = new AudioStream(new FileInputStream("onSelect.wav"));
            BGMData = BGM.getData();
            AudioDataStream loop = null;
            loop = new AudioDataStream(BGMData);
            BGMPlayer.start(loop);
            }
            catch(IOException error)
            {
                System.out.println("Audio play New Game Entered went wrong.");
            }
            
        }
    }//GEN-LAST:event_lblBtnBeginGameClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerName().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBtnBeginGame;
    private javax.swing.JLabel lblBtnMainMenu;
    private javax.swing.JTextField txtPlayerName;
    // End of variables declaration//GEN-END:variables
}
